/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.brvith.operatorsdk.annotation

import com.brvith.operatorsdk.annotation.Library
import org.junit.jupiter.api.Test
import kotlin.test.assertTrue

class LibraryTest {

    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
