/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.brvith.operatorsdk.annotation

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
